<link href="<?php echo URL ?>fonts/fontawesome/css/all.min.css" rel="stylesheet">
<link rel="stylesheet" href="<?php echo URL ?>css/bootstrap.min.css">
<link rel="stylesheet" href="<?php echo URL ?>css/owl.carousel.min.css">
<link rel="stylesheet" href="<?php echo URL ?>css/owl.theme.default.min.css">
<link rel="stylesheet" href="<?php echo URL ?>css/core.min.css">
<link rel="stylesheet" href="<?php echo URL ?>css/shortcode/shortcodes.min.css">
<link rel="stylesheet" href="<?php echo URL ?>style.min.css">
<link rel="stylesheet" href="<?php echo URL ?>css/responsive.min.css">
<link href="<?php echo URL ?>wdadmin/assets/plugins/sweetalert/sweetalert.min.css" rel="stylesheet">